version: '3.1'
services:
  redmine:
    image: redmine
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: redmine
    env_file:
      - redmine.env
    volumes:
      # プラグイン
      - ./work:/usr/src/redmine/plugins/  #←Redmineプラグイン用フォルダ
      - ./log:/usr/src/redmine/log        #←Redmineログフォルダ
      - ./config/database.yml:/usr/src/redmine/config/database.yml       #←Redmineデータベース設定ファイル
    depends_on:
      - db


  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: redmine
      MYSQL_DATABASE: redmine
    volumes:
      # mysqlデータを永続化したいのでマウントする
      - ./mysql_data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci