production:
  adapter: "mysql2"
  host: "db"
  port: "3306"
  username: "root"
  password: "redmine"
  database: "redmine"
development:
  adapter: "mysql2"
  host: "db"
  port: "3306"
  username: "root"
  password: "redmine"
  database: "redmine"